### ISSUE TITLE
Verhindern von XXS

### ISSUE THREAD

**Issue by skeund89** [thegreenonion/lin-todo#37]
Ziel ist cross site scripting zu verhindern, indem in allen Inputs Sonderzeichen verbietet werden.

**Comment by Leg0Batman** [comment]
htmlspecialchars(string,flags,character-set,double_encode) das ist die syntax

**Comment by skeund89** [comment]
Ist fertig. Nach Präsentation kann gemerged werden.

**Comment by Leg0Batman** [comment]
https://habr.com/ru/articles/511318/ schaut mal hier mit Übersetzer das ist perfekt erklärt
